package com.example.live.database

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import kotlinx.coroutines.flow.Flow

@Dao
interface PostDAO {

    @Query("select * from databasepost")
    fun getPosts(): Flow<List<DatabasePost>>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertPosts(vararg posts: DatabasePost)

    @Query("delete from databasepost")
    suspend fun deletePosts()

    /**
     * So that autogenerated key for DatabasePost table will start from 1
     */
    @Query("delete from sqlite_sequence where name='DatabasePost'")
    suspend fun deleteSequence()
}